version: 2.1

orbs:
  flutter: circleci/flutter@1.0.0 # Latest available version of the Flutter Orb

jobs:
  build_and_test:
    docker:
      - image: cimg/base:stable # Use a stable base image
    steps:
      - checkout
      - flutter/install           # Installs Flutter
      - run:
          name: Flutter Doctor
          command: flutter doctor -v # Verify Flutter installation
      - flutter/pub-get           # Fetch dependencies
      - flutter/pub-outdated      # Check for outdated dependencies
      - flutter/test              # Run tests
      - flutter/build:
          type: apk
          build: release          # Build a release APK
      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk # Store the APK

workflows:
  version: 2
  build:
    jobs:
      - build_and_test
