version: 2.1
jobs:
  build:
    docker:
      image: cirrusci/flutter:3.13.7
    steps:
      - checkout
      - run: flutter doctor -v
      - run: flutter pub get
      - run: flutter pub outdated
      - run: flutter test --verbose
      - run: flutter build apk --release
      - store_artifacts:
          path: build/app/outputs/apk/release/app-release.apk


