version: 2.1

jobs:
  build:
    docker:
      - image: cirrusci/flutter:3.19.0
    steps:
      - checkout

      - run:
          name: Set up Flutter
          command: flutter channel stable && flutter upgrade

      - run:
          name: Get Flutter packages
          command: flutter pub get

      - run:
          name: Analyze project source
          command: dart analyze

      - run:
          name: Run Flutter unit tests
          command: flutter test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build