version: 2.1

orbs:
  flutter: circleci/flutter@1.0.0 # Use the latest available version

jobs:
  build_and_test:
    docker:
      - image: cimg/base:stable # Base image; the orb handles Flutter setup
    steps:
      - checkout
      - flutter/install:
          flutter_version: '3.13.7' # Specify the Flutter version you need
      - flutter/pub-get          # Fetch dependencies
      - flutter/pub-outdated     # Check for outdated dependencies
      - flutter/test             # Run Flutter tests
      - flutter/build:
          type: apk
          build: release         # Build the APK
      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk # Store the APK

workflows:
  version: 2
  build:
    jobs:
      - build_and_test
