version: 2.1
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor -v    # Check Flutter/Dart versions
      - run: flutter pub get      # Fetch dependencies
      - run: flutter pub outdated # Check outdated dependencies
      - run: flutter test --verbose # Run tests with detailed logs
      - run: flutter build apk --release # Build the APK
      - store_artifacts:
          path: build/app/outputs/apk/release/app-release.apk


