version: 2.1
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    executor:
      name: default
    steps:
      - checkout
      - run: flutter version 3.13.0 # Pin Flutter version for compatibility
      - run: flutter doctor -v    # Debug Flutter environment
      - run: flutter pub get      # Ensure dependencies are fetched
      - run: flutter pub outdated # Check for outdated dependencies
      - run: flutter test --verbose # Run tests with detailed logs
      - run: flutter build apk --release # Build APK
      - store_artifacts:
          path: build/app/outputs/apk/release/app-release.apk
