const List<String> details = [
'Rise and shine at 5 am to seize the day\'s potential and make room for enriching activities like:\n\n• exercise\n• planning\n• productivity\n• business development.\n\nThese endeavors pave the way for accomplishing greater goals.',
'Write down reflections such as:\n\n• tomorrow\'s aspirations\n• expressions of gratitude\n• contemplation of challenges\n• progress in business.\n\nThese practices can enhance sleep quality and contribute to enhanced mental well-being.',
'Dedicate just 30 minutes a day to learning an online skill! With inflation and taxes on the rise, mastering an online skill can be a transformative move for you.\n\n• coding\n• content creation\n• digital marketing\n• copywriting\n• YouTube',
'Unveil the best versions of yourself through these impactful exercises:\n\n• running\n• swimming\n• weightlifting\n\nIncorporating these exercises will swiftly fortify and sculpt your body.',
'Grant yourself the gift of stillness and mindfulness to:\n\n• pause and reset\n• enhance mental clarity\n• embrace the present moment\n• diminish stress.\n\nPrioritizing moments of calm contributes to a more balanced mindset.',
'Cherish sleep as an essential ally, influencing:\n\n• performance\n• mental well-being\n• stress reduction\n• mood enhancement.\n\nFoster deep and restorative sleep by:\n\n• disconnecting from screens two hours before bedtime\n• refraining from eating two hours before sleep\n• maintaining a cooler sleeping environment\n• utilizing blackout curtains.',
'Nature stands validated as a remedy to:\n\n• dissolve anxiety\n• amplify happiness\n• elevate mood.\n\nEmbrace the outdoors as one of the finest methods to elevate your day.',
'Empower your mind through reading, which simultaneously:\n\n• hones your focus\n• enriches your knowledge\n• bolsters your self-assurance.\n\nCommit to just 10 pages a day for substantial life-long returns.',
'When you say NO to screen time, you unequivocally say YES to something greater.\nEnvision channeling the time spent on your phone into more meaningful pursuits.\n\n1. Monitor and assess your screen time.\n2. Impose limits or employ timers.\n3. Silence notifications.\n4. Embrace grayscale mode.'
];
