const List<String> details = [
  'Rise and shine at 5 am to seize the day\'s potential and make room for enriching activities like:\n\n• exercise\n• planning\n• productivity\n• business development.\n\nThese endeavors pave the way for accomplishing greater goals.',
  'Write down reflections such as:\n\n• tomorrow\'s aspirations\n• expressions of gratitude\n• contemplation of challenges\n• progress in business.\n\nThese practices can enhance sleep quality and contribute to enhanced mental well-being.',
  'Dedicate just 30 minutes a day to learning a new skill! With inflation and taxes on the rise, mastering an new skill can be a transformative move for you.\n\n• coding\n• content creation\n• digital marketing\n• copywriting\n• YouTube\n• calligraphy',
  'Spend at least 1 hour a day exercising. Unveil the best versions of yourself through these impactful exercises:\n\n• running\n• swimming\n• weightlifting\n\nIncorporating these exercises will swiftly fortify and sculpt your body.',
  'Meditate or sit in silence for e.g.10 minutes. Grant yourself the gift of stillness and mindfulness to:\n\n• pause and reset\n• enhance mental clarity\n• embrace the present moment\n• diminish stress.\n\nPrioritizing moments of calm contributes to a more balanced mindset.',
  'Cherish sleep as an essential ally, influencing:\n\n• performance\n• mental well-being\n• stress reduction\n• mood enhancement.\n\nFoster deep and restorative sleep by:\n\n• disconnecting from screens two hours before bedtime\n• refraining from eating two hours before sleep\n• maintaining a cooler sleeping environment\n• utilizing blackout curtains.',
  'Take a walk, especially in nature stands validated as a remedy to:\n\n• dissolve anxiety\n• amplify happiness\n• elevate mood.\n\nEmbrace the outdoors as one of the finest methods to elevate your day.',
  'Empower your mind through reading, which simultaneously:\n\n• hones your focus\n• enriches your knowledge\n• bolsters your self-assurance.',
  'When you say NO to screen time, you unequivocally say YES to something greater.\nEnvision channeling the time spent on your phone into more meaningful pursuits.\n\n1. Monitor and assess your screen time.\n2. Impose limits or employ timers.\n3. Silence notifications.\n4. Embrace grayscale mode.',
  'Quench your body\'s thirst for vitality. Like the early morning rise, hydrating with 2 liters of water sets the tone for an energized day. Each sip nourishes your cells, cleansing and revitalizing from within. Water is your partner in the symphony of well-being.',
  'Embrace a balanced rhythm. Just as you plan and prioritize, moderating caffeine lets your natural energy shine. No more peaks and crashes—just steady alertness, paving the way for harmonious days and restful nights.',
  'Craft your inner narrative with kindness. Your words shape your reality, just as your aspirations shape your business. Speak to yourself as a cherished friend, for self-talk is the canvas upon which dreams are painted.',
  'Infuse your day with thanks. Gratitude, like a new skill, is a key to transformation. It amplifies joy and resilience, turning challenges into stepping stones. Each expression of thankfulness becomes a melody of positivity.',
  'Fuel your body\'s masterpiece. Just as you sculpt with exercise, nourish with vitality. Every meal is a brushstroke of wellness. Choose ingredients that dance with nature\'s palette, composing a symphony of energy within.',
  'Embrace the grace of flexibility. Just as you rise early to seize the day, infuse your body with the fluidity of stretching. Each stretch is a gesture of self-care, a promise to your muscles that you\'ll move through the day with ease. From sunrise to sunset, let your body unfold like the pages of a book, revealing the boundless potential of each moment.',
  'Cultivate the canvas of your passions. As you explore new skills, remember the artistry of your hobbies. Just as you take a 30-minute walk in nature, wander through the landscapes of your interests. Whether it\'s painting, playing an instrument, or crafting, these moments are an oasis of joy and creativity. Honor your hobbies, for they breathe color into the fabric of your life.',
  'Harness the power of breath and movement. Like the sunrise, yoga awakens your body and soul. Each pose is a moment of balance, a gentle reminder that strength and serenity coexist. Through yoga, you create a sanctuary of calm in your day, a space where stress dissipates, and clarity blossoms. Just as you embrace the stillness of meditation, let yoga be your moving meditation—a gift you give yourself for a centered and vibrant life.'
];
